

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ScrollArea } from "@/components/ui/scroll-area";
import ResNavbar from "@/components/reusables/Responsive-Navbar";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Book Publishing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <div className="fixed bg-[url('/bg-home.png')] w-screen h-screen bg-cover bg-center top-0 left-0">
              <ScrollArea className="h-full w-full mt-[94px]">
                <Navbar />
                  {children}
              </ScrollArea>
        </div> */}

        <div className="fixed bg-[url('/bg-home.png')] w-screen h-screen bg-cover bg-center top-0 left-0">
          <ResNavbar />
          <div className="absolute inset-0 top-[94px] overflow-y-auto">
            <ScrollArea className="h-full w-full">
              {children}
            </ScrollArea>
          </div>
        </div>

      </body>
    </html>
  );
}
